# -*- coding: utf-8 -*-
"""Exercícios Recursão.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t4FpyQAyzfV7U2dVPfeep5LTpTJJ3vSG

# Exercícios recursão

## Fatorial

O fatorial de um número inteiro m não negativo, é indicado por m! (lê-se "m fatorial") e é definido pela relação:

m!=m⋅(m−1)⋅(m−2)⋅(m−3)...3⋅2⋅1, para m ≥ 2.

Algumas definições são:

- 1! = 1 (fatorial de 1) - critério de parada
- 0! = 1 (fatorial de 0)

Exemplos:

- 3! = 3 . 2 . 1 = 6
- 4! = 4 . 3 . 2 . 1 = 24
- 6! = 6 . 5 . 4 . 3 . 2 . 1 = 720

Fonte: https://www.infoescola.com/matematica/fatorial/
"""

def fatorial(n):
  if n == 0:
    return 1
  return n * fatorial(n - 1)

fatorial(3)

fatorial(4)

fatorial(6)

"""## Exponenciação

Crie uma função recursiva que calcule o valor de a (base) elevado a b (expoente)

- Se o expoente for zero, a potência é igual 1 (critério de parada)
- Não considere exponenciação de números negativos
"""

def potencia(base, expoente):
  if expoente == 0:
    return 1

  return base * potencia(base, expoente - 1)

potencia(2, 2)

potencia(2, 3)

potencia(2, 4)